// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq15pNvWvfDae1UlXtk-4P2UTEJlYn-n0',
    appId: '1:658888084828:web:c97b1913b0a1711f008599',
    messagingSenderId: '658888084828',
    projectId: 'lambreta-cga',
    authDomain: 'lambreta-cga.firebaseapp.com',
    databaseURL: 'https://lambreta-cga-default-rtdb.firebaseio.com',
    storageBucket: 'lambreta-cga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRb49cRDnHcfxnmBZeACjt9vtWMkPwM0',
    appId: '1:658888084828:android:7dc677181dda7aa3008599',
    messagingSenderId: '658888084828',
    projectId: 'lambreta-cga',
    databaseURL: 'https://lambreta-cga-default-rtdb.firebaseio.com',
    storageBucket: 'lambreta-cga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLtLJ44R6C4d2kV6qlOp1Co8sPspwI58',
    appId: '1:658888084828:ios:c40c14b138eeea36008599',
    messagingSenderId: '658888084828',
    projectId: 'lambreta-cga',
    databaseURL: 'https://lambreta-cga-default-rtdb.firebaseio.com',
    storageBucket: 'lambreta-cga.firebasestorage.app',
    iosBundleId: 'com.example.lambreta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFLtLJ44R6C4d2kV6qlOp1Co8sPspwI58',
    appId: '1:658888084828:ios:c40c14b138eeea36008599',
    messagingSenderId: '658888084828',
    projectId: 'lambreta-cga',
    databaseURL: 'https://lambreta-cga-default-rtdb.firebaseio.com',
    storageBucket: 'lambreta-cga.firebasestorage.app',
    iosBundleId: 'com.example.lambreta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq15pNvWvfDae1UlXtk-4P2UTEJlYn-n0',
    appId: '1:658888084828:web:949f168ef267e99a008599',
    messagingSenderId: '658888084828',
    projectId: 'lambreta-cga',
    authDomain: 'lambreta-cga.firebaseapp.com',
    databaseURL: 'https://lambreta-cga-default-rtdb.firebaseio.com',
    storageBucket: 'lambreta-cga.firebasestorage.app',
  );

}